version: "3.8"
    
services:
  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    #restart: always
    container_name: mysql  
    env_file:
        - .env  
    ports: 
        - 3306:3306
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_CLIENT_USERS: chat
      KAFKA_CLIENT_PASSWORD: secret
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  db_data:    
    driver: local

