
grpc:
  port: 7777
  servercertfile: cert/server-cert.pem
  serverkeyfile: cert/server-key.pem
  clientcacertfile: cert/ca-cert.pem
  clientkeyfile: cert/client-key.pem
  clientcertfile: cert/client-cert.pem
